version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rate-limiter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - RATE_LIMIT_IP=10
      - RATE_LIMIT_TOKEN=100
      - BLOCK_DURATION_SECONDS=300
      - TOKEN_abc123=100
      - TOKEN_xyz789=50
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rate-limiter-network

volumes:
  redis-data:

networks:
  rate-limiter-network:
    driver: bridge
